- name: Breakroom EC2 Setup
  hosts: breakroom
  become: true
  tasks:
    - name: Ensure Python 3 is installed (redundant, but safe)
      yum:
        name: python3
        state: present

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Get latest Docker Compose version number from GitHub
      uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        return_content: yes
      register: compose_release

    - name: Set Docker Compose version
      set_fact:
        docker_compose_version: "{{ compose_release.json.tag_name }}"

    - name: Download Docker Compose binary
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      when: docker_compose_version is defined

    - name: Ensure docker-compose is executable
      file:
        path: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify docker-compose installation
      command: /usr/local/bin/docker-compose --version
      register: docker_compose_check
      changed_when: false

    - name: Install Git and AWS CLI
      yum:
        name:
          - git
          - awscli
        state: present

    - name: Clone the Breakroom repo
      git:
        repo: https://github.com/dallascaley/Breakroom.git
        dest: /home/ec2-user/Breakroom
        version: main
        force: yes
      become: false
      become_user: ec2-user

    - name: Create secrets directory
      file:
        path: /home/ec2-user/backend/etc/encrypt
        state: directory
        recurse: yes
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Download secrets archive from S3
      command: aws s3 cp s3://breakroom-secrets/encrypt.tar.gz /home/ec2-user/encrypt.tar.gz
      become: false
      become_user: ec2-user

    - name: Extract secrets archive
      unarchive:
        src: /home/ec2-user/encrypt.tar.gz
        dest: /home/ec2-user/backend/etc/encrypt
        remote_src: yes
        extra_opts: [--strip-components=1]
      become: false
      become_user: ec2-user

    - name: Download docker-compose.production.yml
      get_url:
        url: https://raw.githubusercontent.com/dallascaley/Breakroom/main/docker-compose.production.yml
        dest: /home/ec2-user/docker-compose.production.yml
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Pull Docker images using Compose (with sudo)
      command: sudo /usr/local/bin/docker-compose -f /home/ec2-user/docker-compose.production.yml pull
      become: false
      become_user: ec2-user
      args:
        chdir: /home/ec2-user

    - name: Start Docker containers using Compose (with sudo)
      command: sudo /usr/local/bin/docker-compose -f /home/ec2-user/docker-compose.production.yml up -d
      become: false
      become_user: ec2-user
      args:
        chdir: /home/ec2-user

