- name: Breakroom EC2 Setup
  hosts: breakroom
  become: true
  tasks:
    - name: Ensure Python 3 is installed (redundant, but safe)
      yum:
        name: python3
        state: present

    - name: Enable NGINX via amazon-linux-extras
      command: amazon-linux-extras enable nginx1
      args:
        creates: /etc/yum.repos.d/amzn2-extras.repo  # avoid running every time

    - name: Install NGINX
      yum:
        name: nginx
        state: present

    - name: Start NGINX service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Get latest Docker Compose version number from GitHub
      uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        return_content: yes
      register: compose_release

    - name: Set Docker Compose version
      set_fact:
        docker_compose_version: "{{ compose_release.json.tag_name }}"

    - name: Download Docker Compose binary
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      when: docker_compose_version is defined

    - name: Verify docker-compose installation
      command: docker-compose --version
      register: docker_compose_check
      changed_when: false